[package]
name = "adventofcode2018"
version = "0.1.0"
authors = ["Antoine Latrille <antoine.latrille@gmail.com>"]
edition = "2018"

[dependencies]
hashbrown = "0.3.0"
regex = "1"
lazy_static = "1.3.0"
chrono = "0.4.6"
